### ISSUE TITLE
EventListener, TriggerTemplate and TriggerBinding resources cannot be instantiated on k8s v1.18 w/ ServerSideApply enabled

### ISSUE THREAD

**Issue by ghglza** [tektoncd/triggers#539] opened 2020-04-16 11:54 UTC
Starting in k8s v1.18, ServerSideApply is promoted to beta, and the feature gate enabled per default.

# Expected Behavior
It should be possible to instantiate Tekton Triggers resources on k8s v1.18 w/ ServerSideApply enabled

# Actual Behavior
Instantiation fails for EventListener, TriggerBinding and TriggerTemplate resources with error message

```
Error from server (BadRequest): error when creating "roles/k8scustom/files/tekton-triggers-smoketest.yml": admission webhook "triggers-webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "managedFields"
```

This does not happen if the k8s v1.18.1 API server is configured with

```
--feature-gate ServerSideApply=false
```

# Steps to Reproduce the Problem

1. Install k8s v1.18.1, with ServerSideApply enabled
2. Try to instantiate Tekton Triggers EventListener, TriggerBinding or TriggerTemplate resource

# Additional Info
k8s v1.18.1 provisioned via kubeadm on Centos 7, running on VMWare
Tekton Triggers 0.3.1 and 0.4.0

**Comment by vdemeester** [comment] 2020-04-16 12:06
@ghglza This is also an issue on `tektoncd/pipeline` by the way

/cc @bobcatfish @dibyom 
/kind bug

**Comment by vdemeester** [comment] 2020-04-16 12:06
(I think we should create an issue on `tektoncd/pipeline` too :wink:)

**Comment by ghglza** [comment] 2020-04-16 13:32
Sorry I'm not sure this warrants also a tektoncd/pipeline issue -- creating Condition, Pipeline, and Task resources worked for us when the ServerSideApply feature gate was enabled.
Only trigger resources were affected: another look in the error log revealed that creation failed not only for EventListener, but also forTriggerTemplate and TriggerBinding (maybe the title of this issue should be changed to reflect this?)

**Comment by vdemeester** [comment] 2020-04-16 13:34
> Sorry I'm not sure this warrants also a tektoncd/pipeline issue -- creating Condition, Pipeline, and Task resources worked for us when the ServerSideApply feature gate was enabled.

Interesting, we did have that issue while testing Pipelines only (no triggers) on OpenShift 4.5.x (which ships k8s 1.18)… but maybe it got fixed somehow in tektoncd/pipeline, I need to try again…

> Only trigger resources were affected: another look in the error log revealed that creation failed not only for EventListener, but also forTriggerTemplate and TriggerBinding (maybe the title of this issue should be changed to reflect this?)

Yes :+1:

**Comment by dibyom** [comment] 2020-04-16 14:47
Interesting...any idea what the difference is in the Pipeline types that allows them to work with server side apply?

**Comment by vdemeester** [comment] 2020-04-16 14:59
@dibyom it could also be the `knative.dev/pkg` *or* the `k8s.io/*` dependencies that differ :angel:

**Comment by dibyom** [comment] 2020-04-20 18:54
So, I failed to reproduce on my local environment using minikube. My EventListener got created successfully and it could create Taskruns as well. I confirmed that serverSideApply was enabled since if i do a kubectl get on the resource, the `metadata` contains a ` [managedFields](https://kubernetes.io/docs/reference/using-api/api-concepts/#field-management)` field.

@ghglza are you still running into this issue? If so, some of the webhook logs might help.


Steps:
1. ` minikube start --kubernetes-version=v1.18.1 --feature-gates=ServerSideApply=true`
1.  `kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/v0.11.2/release.yaml`
1. ` kubectl apply -f https://github.com/tektoncd/triggers/releases/download/v0.4.0/release.yaml`
1.  `kubectl apply -f examples/role-resources/ && kubectl apply -f examples/role-resources/triggerbinding-roles`
1. `kubectl apply -f examples/gitlab/gitlab-push-listener.yaml`

**Comment by ghglza** [comment] 2020-04-21 13:56
The error is gone for us, too:
After upgrading to k8s v1.18.2 (and several newer commits of CRI-O), our Triggers deployment bailed out due to RBAC errors on our side (failed to adapt to the changed API group name) -- but these were reported clearly, and easily fixed.
So from my perspective, this can be closed as bug.

**Comment by dibyom** [comment] 2020-04-21 14:53
Cool! Will close the issue. Please reopen if you notice this again!
/close

**Closed by dibyom** 2020-04-21 14:53 UTC
Labels: kind/bug
