### ISSUE TITLE
cel filter error

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/triggers#952] opened 2021-02-10 02:41 UTC
# Expected Behavior

I have the following EventListener

```bash
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-pipeline-trigger-event-listener
spec:
  serviceAccountName: triggers-sa
  triggers:
  - name: github-listener
    interceptors:
    - github:
        eventTypes:
        - push
    - cel:
        filter: >-
          "body.ref == 'refs/heads/main' && body.head_commit.id != null"

    bindings:
    - ref: build-pipeline-trigger-binding
    template:
      name: build-pipeline-trigger-template
```

When I imitate the event with curl:

```bash
➜ curl -i \
  -H 'X-GitHub-Event: push' \
  -H 'X-Hub-Signature: sha1=c231f55204706a1c9717d541c8e0e1670c484a3f' \
  -H 'Content-Type: application/json' \
  -d '{"ref":"refs/heads/main","head_commit":{"id":"d9c7ccb0713da882d8373169e2a1d705f5959386"}}' \
  https://webhook.domain.com/backend
HTTP/2 202 
date: Wed, 10 Feb 2021 02:31:50 GMT
content-type: application/json
content-length: 95
strict-transport-security: max-age=15724800; includeSubDomains

{"eventListener":"build-pipeline-trigger-event-listener","namespace":"prod","eventID":"8nt2k"}

```

I get the following error in event listener pod:

```bash
{"level":"info","ts":"2021-02-10T02:31:50.323Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression \"body.ref == 'refs/heads/main' && body.head_commit.id != null\" did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"8nt2k","/trigger":"github-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

I tried `"body.ref == 'refs/heads/main' && body.head_commit != null"` but that still gave me the same error.

What am I doing wrong? I checked the https://github.com/google/cel-spec/blob/master/doc/langdef.md and it seems the **null** is supported.

# Actual Behavior

I am getting the error 

# Additional Info

- Kubernetes version:

 ```bash
✦2 ➜ kubectl version                                                             
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```bash
✦2 ➜ tkn version                                     
Client version: 0.15.0
Pipeline version: v0.15.2
Triggers version: v0.11.2

```

**Comment by bigkevmcd** [comment] 2021-02-10 06:54
Hello @dmitry-mightydevops I've had a look at this, and reproduced it locally.

The CEL implementation in use is https://github.com/google/cel-go and looking at the code, the only thing you can compare `null` with seems to be `null`, which is unfortunate, and I don't have a workaround for this.

I've opened an issue in the upstream CEL implementation.

**Comment by dmitry-mightydevops** [comment] 2021-02-10 07:18
thank you @bigkevmcd!

**Comment by jmcshane** [comment] 2021-04-11 01:07
@dmitry-mightydevops looking at the upstream issue, that project won't be resolving the null comparison issue. One thing I was wondering is if you have tried the `has` function. You can use this to check whether an entry is present in a JSON document. Try to update your filter to:

```
"body.ref == 'refs/heads/main' && has(body.head_commit)"
```

**Comment by frerikandriessen** [comment] 2021-07-27 14:48
For anyone who's interested, I ran into the same issue and I worked around it by comparing the type, since the null type is reserved for null values. Like so:
`type(body.head_commit.id) != type(null)`

**Closed** 2021-11-14 03:05 UTC
Labels: lifecycle/rotten, kind/bug
