### ISSUE TITLE
0.6.0: CEL: compareSecrets error:found no matching overload for '_&&_' applied to '(bool, string)'\n 

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#644] opened 2020-06-28 15:58 UTC
This works:
```
  filter: >-
    header.match('x-h1', 'v1') && 
    header.match('x-h2', 'secret1LiteralVal') && 
    has(body.resource.repository.name) && 
    !has(body.resource.commits) && 
    body.resource.refUpdates[0].newObjectId != '0000000000000000000000000000000000000000'
```

This fails:
```
  filter: >-
    header.match('x-h1', 'v1') && 
    header.canonical('x-h2').compareSecret('secretKey1','my-secret-in-tekton-ns') && 
    has(body.resource.repository.name) && 
    !has(body.resource.commits) && 
    body.resource.refUpdates[0].newObjectId != '0000000000000000000000000000000000000000'
```

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:215","msg":"failed to evaluate expression
 'header.match('x-h1', 'v1') &&  
 header.canonical('x-h2').compareSecret('secretKey1','my-secret-in-tekton-ns') && 
  has(body.resource.repository.name) &&  !has(body.resource.commits) && 
   body.resource.refUpdates[0].newObjectId != '0000000000000000000000000000000000000000'': 
   ERROR: <input>:1:47: found no matching overload for '_&&_' applied to '(bool, string)'\n | header.match('x-h1', 'v1') &&  
   header.canonical('x-h2').compareSecret('secretKey1','my-secret-in-tekton-ns') && 
    has(body.resource.repository.name) &&  !has(body.resource.commits) &&  body.resource.refUpdates[0].newObjectId != '0000000000000000000000000000000000000000'\n 
    | ..............................................^","knative.dev/controller":"eventlistener","/triggers-eventid":"x8wtb","/trigger":"my-git-build-v1-interceptor",
"stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.executeInterceptors\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:215\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:144\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:94"}
```

**Comment by bigkevmcd** [comment] 2020-06-29 14:03
This looks like a CEL issue, rather than a `triggers`?

My guess is that it's an operator precedence issue

The `_&&_` looks to me like `header.match('x-h1', 'v1') && header.canonical('x-h2')`

I wonder if adding brackets to `header.canonical('x-h2').compareSecret('secretKey1','my-secret-in-tekton-ns')` this would fix it?

**Comment by bitsofinfo** [comment] 2020-06-29 14:04
You mean like `(header.canonical('x-h2').compareSecret('secretKey1','my-secret-in-tekton-ns'))`?

**Comment by bigkevmcd** [comment] 2020-06-29 14:24
@bitsofinfo Yes, I _think_ that's the expression that's breaking it.

**Comment by bitsofinfo** [comment] 2020-06-29 15:18
@bigkevmcd tried that, I get the same error

**Comment by TristonianJones** [comment] 2020-07-02 17:10
Hi All, the issue is the return type declaration for `compareSecret` should be `decls.Bool`, but the last argument (the return type) is listed as `decls.String`:

https://github.com/tektoncd/triggers/blob/5348837b14624898ff67b1e7c4b72a6f03982415/pkg/interceptors/cel/triggers.go#L179-L181

**Comment by bigkevmcd** [comment] 2020-07-02 17:36
@bitsofinfo thanks, sorry about that, should be fixed...

**Comment by bigkevmcd** [comment] 2020-07-02 17:36
@bitsofinfo and thanks for debugging it!

**Comment by bitsofinfo** [comment] 2020-07-02 17:37
solid thx, will be out in next release?

**Comment by TristonianJones** [comment] 2020-07-02 18:03
I will accept some blame here since the call signature for creating function declarations could definitely be more intuitive. Feel free to mention me if you ever want an extra pair of eyes.

**Closed** 2020-07-06 15:50 UTC
