### ISSUE TITLE
Update EventListener to consume CloudEvent

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#39] opened 2019-07-23 15:18 UTC
# Expected Behavior

Once we have #36 the next step is for the running binary to expose a Knative addressable endpoint that can be invoked with a CloudEvent!

It doesn't have to actually do anything with the CloudEvent at this point but maybe could log something fun?

# Actual Behavior

Once we have #36 we'll have a running pod but it won't be listening for CloudEvents yet

# Additional Info

If we have #37 at this point, we should expand the end to end test to hit the running EventListener with a predefined CloudEvent. If not, we'll need to create a follow up issue in the #33 epic to add that to the end to end test.

**Comment by vtereso** [comment] 2019-07-24 18:20
From what I have discovered, vendors (GitHub, DockerHub, etc.) do not emit CloudEvents and it would be necessary to have some middle-layer such as Knative eventing to generate them. Parsing of the CloudEvent structure is supported just like any other (arbitrary payload), but since there is an overhead to generate this it seems unnecessary to have Trigger/this work item use Knative and CloudEvents. Some people have already expressed interest to avoid using Knative. Should someone opt to use it however, it would be simple enough for configure a rediretion from the Knative sync to the Triggers addressable service. So in short, maybe we should not be directly supporting CloudEvent or Knative.

**Comment by vincent-pli** [comment] 2019-07-25 02:41
I think we need make decision before really implementation.
I prefer to support `CouldEvent`, reasons:
1. That's true the vendors do not emit `CouldEvent` but we can leverage `knative-contrib` to do the translation, the problem is some sources in `knative-contrib` is depends on `knative-serving`, like `github source`, I guess maybe we need implements ourselves.
2. Without `CloudEvent` we need define tekton's event/message structure, same, the vendor do not emit it, we also need middleware. Furthermore, I remember we try to do `filter` based on `event`. so `Couldevent` is a good available choice.

I think we try to avoid depends on `Knative` directly, `CloudEvent` is ok I guess.

BTW. I wonder to know how to expose our `receiver/listener`(deployment) to outer world?
k8s `Service` or `Ingress`, `istio`? or leave to end user?

**Comment by vtereso** [comment] 2019-07-25 13:18
> I think we need make decision before really implementation.
> I prefer to support `CouldEvent`, reasons:
> 
>     1. That's true the vendors do not emit `CouldEvent` but we can leverage `knative-contrib` to do the translation, the problem is some sources in `knative-contrib` is depends on `knative-serving`, like `github source`, I guess maybe we need implements ourselves.
> 
>     2. Without `CloudEvent` we need define tekton's event/message structure, same, the vendor do not emit it, we also need middleware. Furthermore, I remember we try to do `filter` based on `event`. so `Couldevent` is a good available choice.
> 
> 
> I think we try to avoid depends on `Knative` directly, `CloudEvent` is ok I guess.
> 
> BTW. I wonder to know how to expose our `receiver/listener`(deployment) to outer world?
> k8s `Service` or `Ingress`, `istio`? or leave to end user?

We will be discussing this briefly and will update the issue.

**Comment by bobcatfish** [comment] 2019-07-26 14:37
Note discussion continuing in https://github.com/tektoncd/triggers/issues/42

**Comment by vtereso** [comment] 2019-08-06 13:11
This can be closed out since it will be addressed in https://github.com/tektoncd/triggers/issues/47?

**Comment by ncskier** [comment] 2019-08-06 13:29
This technically works right now, but if we want to be able to use our Service as a Knative Eventing sink, then we need to expose port `80`. I would think that's part of this work item since Knative Eventing is the only eventing source I know of that sends CloudEvents, but we can open a new issue if that is preferred. @EliZucker what do you think?

**Comment by EliZucker** [comment] 2019-08-06 16:54
Our [agreed upon proposal](https://github.com/tektoncd/triggers/issues/42#issuecomment-516854462) includes becoming a (Knative) addressable endpoint, and in order to do that we:

> MUST expose a status.address.hostname

(according to the knative interface docs). Since that's part of this issue and we haven't done that yet I think this issue should stay open for now. There's also the separate question of exposing ports (I'm hoping we can let users specify that?), and I'm not sure how that fits into this issue.

**Closed** 2019-10-01 19:23 UTC
